name: github_hook
version: 0.2.2+1
description: A Shelf handler for managed GitHub hook messages
author: Kevin Moore <kevmoo@google.com>
homepage: https://github.com/kevmoo/github_hook.dart
environment:
  sdk: '>=1.17.0 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.14.0'
  convert: '^2.0.0'
  crypto: '^2.0.1'
  shelf: '>=0.6.0 <0.7.0'
dev_dependencies:
  path: ^1.3.5
  test: '^0.12.0'
